version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: expense_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: expensedb
      MYSQL_USER: expenseuser
      MYSQL_PASSWORD: expensepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "expenseuser",
          "-pexpensepass",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: expense_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: expenseuser
      DB_PASSWORD: expensepass
      DB_NAME: expensedb
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
